version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo "deb https://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
      - curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | apt-key add
      - apt-get update -y
      - apt-get install -y sbt
  pre_build:
    commands:
      - echo "Creating artifact"
  build:
    commands:
      - sbt package
  post_build:
    commands:
      - echo "Done"

artifacts:
  files:
    - appspec.yml
    - codedeploy-scripts/run_job.sh
    - src/main/resources/*.csv
    - scripts/create_index.py
    - target/scala-2.11/spark-covid_2.11-1.0.jar  
  discard-paths: yes